// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lodging/chatMessage.proto

package lodging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor that produced the message.
type Sender int32

const (
	// Default zero value.
	Sender_SENDER_UNSPECIFIED Sender = 0
	// Guest-originated message.
	Sender_SENDER_GUEST Sender = 1
	// System-originated message.
	Sender_SENDER_SYSTEM Sender = 2
)

// Enum value maps for Sender.
var (
	Sender_name = map[int32]string{
		0: "SENDER_UNSPECIFIED",
		1: "SENDER_GUEST",
		2: "SENDER_SYSTEM",
	}
	Sender_value = map[string]int32{
		"SENDER_UNSPECIFIED": 0,
		"SENDER_GUEST":       1,
		"SENDER_SYSTEM":      2,
	}
)

func (x Sender) Enum() *Sender {
	p := new(Sender)
	*p = x
	return p
}

func (x Sender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sender) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_chatMessage_proto_enumTypes[0].Descriptor()
}

func (Sender) Type() protoreflect.EnumType {
	return &file_lodging_chatMessage_proto_enumTypes[0]
}

func (x Sender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sender.Descriptor instead.
func (Sender) EnumDescriptor() ([]byte, []int) {
	return file_lodging_chatMessage_proto_rawDescGZIP(), []int{0}
}

// Acknowledgment outcome.
type AckStatus int32

const (
	// Default zero value.
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	// Message accepted and processed.
	AckStatus_ACK_STATUS_ACCEPTED AckStatus = 1
	// Message rejected and not processed.
	AckStatus_ACK_STATUS_REJECTED AckStatus = 2
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_ACCEPTED",
		2: "ACK_STATUS_REJECTED",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_ACCEPTED":    1,
		"ACK_STATUS_REJECTED":    2,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_chatMessage_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_lodging_chatMessage_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_lodging_chatMessage_proto_rawDescGZIP(), []int{1}
}

// Stable machine-readable error codes for protocol and domain handling.
type ErrorCode int32

const (
	// Default zero value.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// No error / successful processing.
	ErrorCode_ERROR_CODE_NONE ErrorCode = 1
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_NONE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"ERROR_CODE_NONE":        1,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_chatMessage_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_lodging_chatMessage_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_lodging_chatMessage_proto_rawDescGZIP(), []int{2}
}

// Transport envelope used for websocket exchange between guest and system.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Correlates request/response pairs across messages.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Originating actor.
	Sender Sender `protobuf:"varint,4,opt,name=sender,proto3,enum=lodging.v1.Sender" json:"sender,omitempty"`
	// Protocol contract version (for example: "lodging.v1").
	ProtocolVersion string `protobuf:"bytes,12,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Per-message trace propagation payload.
	TraceContext map[string]string `protobuf:"bytes,13,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Exactly one payload variant per envelope.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatMessage_GuestAction
	//	*ChatMessage_GuestResponse
	//	*ChatMessage_SystemNotification
	//	*ChatMessage_SystemRequest
	//	*ChatMessage_Ack
	Payload       isChatMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_lodging_chatMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_chatMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_lodging_chatMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessage) GetSender() Sender {
	if x != nil {
		return x.Sender
	}
	return Sender_SENDER_UNSPECIFIED
}

func (x *ChatMessage) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ChatMessage) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *ChatMessage) GetPayload() isChatMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatMessage) GetGuestAction() GuestAction {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_GuestAction); ok {
			return x.GuestAction
		}
	}
	return GuestAction_GUEST_ACTION_UNSPECIFIED
}

func (x *ChatMessage) GetGuestResponse() *GuestResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_GuestResponse); ok {
			return x.GuestResponse
		}
	}
	return nil
}

func (x *ChatMessage) GetSystemNotification() SystemNotification {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_SystemNotification); ok {
			return x.SystemNotification
		}
	}
	return SystemNotification_SYSTEM_NOTIFICATION_UNSPECIFIED
}

func (x *ChatMessage) GetSystemRequest() SystemRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_SystemRequest); ok {
			return x.SystemRequest
		}
	}
	return SystemRequest_SYSTEM_REQUEST_UNSPECIFIED
}

func (x *ChatMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_GuestAction struct {
	// Guest-initiated lifecycle action.
	GuestAction GuestAction `protobuf:"varint,6,opt,name=guest_action,json=guestAction,proto3,enum=lodging.v1.GuestAction,oneof"`
}

type ChatMessage_GuestResponse struct {
	// Guest data/action response to a system request.
	GuestResponse *GuestResponse `protobuf:"bytes,7,opt,name=guest_response,json=guestResponse,proto3,oneof"`
}

type ChatMessage_SystemNotification struct {
	// Informational event emitted by the system.
	SystemNotification SystemNotification `protobuf:"varint,8,opt,name=system_notification,json=systemNotification,proto3,enum=lodging.v1.SystemNotification,oneof"`
}

type ChatMessage_SystemRequest struct {
	// Action/data request emitted by the system.
	SystemRequest SystemRequest `protobuf:"varint,9,opt,name=system_request,json=systemRequest,proto3,enum=lodging.v1.SystemRequest,oneof"`
}

type ChatMessage_Ack struct {
	// Delivery/processing acknowledgment for a prior message.
	Ack *Ack `protobuf:"bytes,10,opt,name=ack,proto3,oneof"`
}

func (*ChatMessage_GuestAction) isChatMessage_Payload() {}

func (*ChatMessage_GuestResponse) isChatMessage_Payload() {}

func (*ChatMessage_SystemNotification) isChatMessage_Payload() {}

func (*ChatMessage_SystemRequest) isChatMessage_Payload() {}

func (*ChatMessage_Ack) isChatMessage_Payload() {}

// Acknowledges a previously received message.
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID being acknowledged.
	AcknowledgedMessageId string `protobuf:"bytes,1,opt,name=acknowledged_message_id,json=acknowledgedMessageId,proto3" json:"acknowledged_message_id,omitempty"`
	// Ack processing result.
	Status AckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=lodging.v1.AckStatus" json:"status,omitempty"`
	// Machine-readable result code. Clients should branch on this value.
	Code          ErrorCode `protobuf:"varint,3,opt,name=code,proto3,enum=lodging.v1.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_lodging_chatMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_chatMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_lodging_chatMessage_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetAcknowledgedMessageId() string {
	if x != nil {
		return x.AcknowledgedMessageId
	}
	return ""
}

func (x *Ack) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *Ack) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

var File_lodging_chatMessage_proto protoreflect.FileDescriptor

const file_lodging_chatMessage_proto_rawDesc = "" +
	"\n" +
	"\x19lodging/chatMessage.proto\x12\n" +
	"lodging.v1\x1a\x13lodging/guest.proto\x1a\x14lodging/system.proto\"\x84\x05\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12*\n" +
	"\x06sender\x18\x04 \x01(\x0e2\x12.lodging.v1.SenderR\x06sender\x12)\n" +
	"\x10protocol_version\x18\f \x01(\tR\x0fprotocolVersion\x12N\n" +
	"\rtrace_context\x18\r \x03(\v2).lodging.v1.ChatMessage.TraceContextEntryR\ftraceContext\x12<\n" +
	"\fguest_action\x18\x06 \x01(\x0e2\x17.lodging.v1.GuestActionH\x00R\vguestAction\x12B\n" +
	"\x0eguest_response\x18\a \x01(\v2\x19.lodging.v1.GuestResponseH\x00R\rguestResponse\x12Q\n" +
	"\x13system_notification\x18\b \x01(\x0e2\x1e.lodging.v1.SystemNotificationH\x00R\x12systemNotification\x12B\n" +
	"\x0esystem_request\x18\t \x01(\x0e2\x19.lodging.v1.SystemRequestH\x00R\rsystemRequest\x12#\n" +
	"\x03ack\x18\n" +
	" \x01(\v2\x0f.lodging.v1.AckH\x00R\x03ack\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\x97\x01\n" +
	"\x03Ack\x126\n" +
	"\x17acknowledged_message_id\x18\x01 \x01(\tR\x15acknowledgedMessageId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.lodging.v1.AckStatusR\x06status\x12)\n" +
	"\x04code\x18\x03 \x01(\x0e2\x15.lodging.v1.ErrorCodeR\x04code*E\n" +
	"\x06Sender\x12\x16\n" +
	"\x12SENDER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSENDER_GUEST\x10\x01\x12\x11\n" +
	"\rSENDER_SYSTEM\x10\x02*Y\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACK_STATUS_ACCEPTED\x10\x01\x12\x17\n" +
	"\x13ACK_STATUS_REJECTED\x10\x02*<\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x01BJZHgithub.com/Kenji-Uema/guestSimulator/internal/domain/dto/lodging;lodgingb\x06proto3"

var (
	file_lodging_chatMessage_proto_rawDescOnce sync.Once
	file_lodging_chatMessage_proto_rawDescData []byte
)

func file_lodging_chatMessage_proto_rawDescGZIP() []byte {
	file_lodging_chatMessage_proto_rawDescOnce.Do(func() {
		file_lodging_chatMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lodging_chatMessage_proto_rawDesc), len(file_lodging_chatMessage_proto_rawDesc)))
	})
	return file_lodging_chatMessage_proto_rawDescData
}

var file_lodging_chatMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lodging_chatMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lodging_chatMessage_proto_goTypes = []any{
	(Sender)(0),             // 0: lodging.v1.Sender
	(AckStatus)(0),          // 1: lodging.v1.AckStatus
	(ErrorCode)(0),          // 2: lodging.v1.ErrorCode
	(*ChatMessage)(nil),     // 3: lodging.v1.ChatMessage
	(*Ack)(nil),             // 4: lodging.v1.Ack
	nil,                     // 5: lodging.v1.ChatMessage.TraceContextEntry
	(GuestAction)(0),        // 6: lodging.v1.GuestAction
	(*GuestResponse)(nil),   // 7: lodging.v1.GuestResponse
	(SystemNotification)(0), // 8: lodging.v1.SystemNotification
	(SystemRequest)(0),      // 9: lodging.v1.SystemRequest
}
var file_lodging_chatMessage_proto_depIdxs = []int32{
	0, // 0: lodging.v1.ChatMessage.sender:type_name -> lodging.v1.Sender
	5, // 1: lodging.v1.ChatMessage.trace_context:type_name -> lodging.v1.ChatMessage.TraceContextEntry
	6, // 2: lodging.v1.ChatMessage.guest_action:type_name -> lodging.v1.GuestAction
	7, // 3: lodging.v1.ChatMessage.guest_response:type_name -> lodging.v1.GuestResponse
	8, // 4: lodging.v1.ChatMessage.system_notification:type_name -> lodging.v1.SystemNotification
	9, // 5: lodging.v1.ChatMessage.system_request:type_name -> lodging.v1.SystemRequest
	4, // 6: lodging.v1.ChatMessage.ack:type_name -> lodging.v1.Ack
	1, // 7: lodging.v1.Ack.status:type_name -> lodging.v1.AckStatus
	2, // 8: lodging.v1.Ack.code:type_name -> lodging.v1.ErrorCode
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_lodging_chatMessage_proto_init() }
func file_lodging_chatMessage_proto_init() {
	if File_lodging_chatMessage_proto != nil {
		return
	}
	file_lodging_guest_proto_init()
	file_lodging_system_proto_init()
	file_lodging_chatMessage_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatMessage_GuestAction)(nil),
		(*ChatMessage_GuestResponse)(nil),
		(*ChatMessage_SystemNotification)(nil),
		(*ChatMessage_SystemRequest)(nil),
		(*ChatMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lodging_chatMessage_proto_rawDesc), len(file_lodging_chatMessage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lodging_chatMessage_proto_goTypes,
		DependencyIndexes: file_lodging_chatMessage_proto_depIdxs,
		EnumInfos:         file_lodging_chatMessage_proto_enumTypes,
		MessageInfos:      file_lodging_chatMessage_proto_msgTypes,
	}.Build()
	File_lodging_chatMessage_proto = out.File
	file_lodging_chatMessage_proto_goTypes = nil
	file_lodging_chatMessage_proto_depIdxs = nil
}
