// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lodging/guest.proto

package lodging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actions initiated by a guest during the stay lifecycle.
type GuestAction int32

const (
	// Default zero value.
	GuestAction_GUEST_ACTION_UNSPECIFIED GuestAction = 0
	// Guest arrives to start check-in.
	GuestAction_SHOW_FOR_CHECKIN    GuestAction = 1
	GuestAction_SHOW_DOCUMENT       GuestAction = 2
	GuestAction_SHOW_BOOKING_NUMBER GuestAction = 3
	// Guest enters the assigned cottage.
	GuestAction_ENTER_COTTAGE GuestAction = 4
	// Guest leaves the assigned cottage.
	GuestAction_LEAVE_COTTAGE GuestAction = 5
	// Guest leaves cottage to use bath facilities.
	GuestAction_GO_FOR_A_BATH GuestAction = 6
	// Guest comes back from bath facilities.
	GuestAction_RETURN_FROM_BATH GuestAction = 7
	// Guest goes to dinner.
	GuestAction_GO_FOR_DINNER GuestAction = 8
	// Guest goes to breakfast.
	GuestAction_GO_FOR_BREAKFAST GuestAction = 9
	// Guest goes to sleep.
	GuestAction_GO_TO_SLEEP GuestAction = 10
	// Guest wakes up.
	GuestAction_WAKEUP GuestAction = 11
	// Guest notifies they are leaving for cleanup.
	GuestAction_LEAVE_CLEANUP_NOTIFICATION GuestAction = 12
	// Guest stays in resort common areas.
	GuestAction_ENJOY_RESORT GuestAction = 13
	// Guest proceeds to checkout process.
	GuestAction_PROCEED_TO_CHECKOUT GuestAction = 14
	GuestAction_RETURN_COTTAGE_KEY  GuestAction = 15
	GuestAction_TAKE_COTTAGE_KEY    GuestAction = 16
)

// Enum value maps for GuestAction.
var (
	GuestAction_name = map[int32]string{
		0:  "GUEST_ACTION_UNSPECIFIED",
		1:  "SHOW_FOR_CHECKIN",
		2:  "SHOW_DOCUMENT",
		3:  "SHOW_BOOKING_NUMBER",
		4:  "ENTER_COTTAGE",
		5:  "LEAVE_COTTAGE",
		6:  "GO_FOR_A_BATH",
		7:  "RETURN_FROM_BATH",
		8:  "GO_FOR_DINNER",
		9:  "GO_FOR_BREAKFAST",
		10: "GO_TO_SLEEP",
		11: "WAKEUP",
		12: "LEAVE_CLEANUP_NOTIFICATION",
		13: "ENJOY_RESORT",
		14: "PROCEED_TO_CHECKOUT",
		15: "RETURN_COTTAGE_KEY",
		16: "TAKE_COTTAGE_KEY",
	}
	GuestAction_value = map[string]int32{
		"GUEST_ACTION_UNSPECIFIED":   0,
		"SHOW_FOR_CHECKIN":           1,
		"SHOW_DOCUMENT":              2,
		"SHOW_BOOKING_NUMBER":        3,
		"ENTER_COTTAGE":              4,
		"LEAVE_COTTAGE":              5,
		"GO_FOR_A_BATH":              6,
		"RETURN_FROM_BATH":           7,
		"GO_FOR_DINNER":              8,
		"GO_FOR_BREAKFAST":           9,
		"GO_TO_SLEEP":                10,
		"WAKEUP":                     11,
		"LEAVE_CLEANUP_NOTIFICATION": 12,
		"ENJOY_RESORT":               13,
		"PROCEED_TO_CHECKOUT":        14,
		"RETURN_COTTAGE_KEY":         15,
		"TAKE_COTTAGE_KEY":           16,
	}
)

func (x GuestAction) Enum() *GuestAction {
	p := new(GuestAction)
	*p = x
	return p
}

func (x GuestAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuestAction) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_guest_proto_enumTypes[0].Descriptor()
}

func (GuestAction) Type() protoreflect.EnumType {
	return &file_lodging_guest_proto_enumTypes[0]
}

func (x GuestAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuestAction.Descriptor instead.
func (GuestAction) EnumDescriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{0}
}

// Data supplied by a guest in response to a system request.
type GuestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one guest response payload per message.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*GuestResponse_ShowDocument
	//	*GuestResponse_ShowBookingNumber
	//	*GuestResponse_ReceiveCottageKey
	//	*GuestResponse_ReturnCottageKey
	Payload       isGuestResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestResponse) Reset() {
	*x = GuestResponse{}
	mi := &file_lodging_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestResponse) ProtoMessage() {}

func (x *GuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestResponse.ProtoReflect.Descriptor instead.
func (*GuestResponse) Descriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{0}
}

func (x *GuestResponse) GetPayload() isGuestResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GuestResponse) GetShowDocument() *ShowDocument {
	if x != nil {
		if x, ok := x.Payload.(*GuestResponse_ShowDocument); ok {
			return x.ShowDocument
		}
	}
	return nil
}

func (x *GuestResponse) GetShowBookingNumber() *ShowBookingNumber {
	if x != nil {
		if x, ok := x.Payload.(*GuestResponse_ShowBookingNumber); ok {
			return x.ShowBookingNumber
		}
	}
	return nil
}

func (x *GuestResponse) GetReceiveCottageKey() *ReceiveCottageKey {
	if x != nil {
		if x, ok := x.Payload.(*GuestResponse_ReceiveCottageKey); ok {
			return x.ReceiveCottageKey
		}
	}
	return nil
}

func (x *GuestResponse) GetReturnCottageKey() *ReturnCottageKey {
	if x != nil {
		if x, ok := x.Payload.(*GuestResponse_ReturnCottageKey); ok {
			return x.ReturnCottageKey
		}
	}
	return nil
}

type isGuestResponse_Payload interface {
	isGuestResponse_Payload()
}

type GuestResponse_ShowDocument struct {
	// Guest provides a document identifier.
	ShowDocument *ShowDocument `protobuf:"bytes,1,opt,name=show_document,json=showDocument,proto3,oneof"`
}

type GuestResponse_ShowBookingNumber struct {
	// Guest provides a booking identifier.
	ShowBookingNumber *ShowBookingNumber `protobuf:"bytes,2,opt,name=show_booking_number,json=showBookingNumber,proto3,oneof"`
}

type GuestResponse_ReceiveCottageKey struct {
	// Guest confirms they received a cottage key.
	ReceiveCottageKey *ReceiveCottageKey `protobuf:"bytes,3,opt,name=receive_cottage_key,json=receiveCottageKey,proto3,oneof"`
}

type GuestResponse_ReturnCottageKey struct {
	// Guest confirms they returned a cottage key.
	ReturnCottageKey *ReturnCottageKey `protobuf:"bytes,4,opt,name=return_cottage_key,json=returnCottageKey,proto3,oneof"`
}

func (*GuestResponse_ShowDocument) isGuestResponse_Payload() {}

func (*GuestResponse_ShowBookingNumber) isGuestResponse_Payload() {}

func (*GuestResponse_ReceiveCottageKey) isGuestResponse_Payload() {}

func (*GuestResponse_ReturnCottageKey) isGuestResponse_Payload() {}

// Guest shares a document identifier.
type ShowDocument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resort-issued or booking-linked document ID.
	DocumentId    string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowDocument) Reset() {
	*x = ShowDocument{}
	mi := &file_lodging_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDocument) ProtoMessage() {}

func (x *ShowDocument) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDocument.ProtoReflect.Descriptor instead.
func (*ShowDocument) Descriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ShowDocument) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// Guest shares a booking identifier.
type ShowBookingNumber struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reservation/booking ID.
	BookingId     string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowBookingNumber) Reset() {
	*x = ShowBookingNumber{}
	mi := &file_lodging_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowBookingNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowBookingNumber) ProtoMessage() {}

func (x *ShowBookingNumber) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowBookingNumber.ProtoReflect.Descriptor instead.
func (*ShowBookingNumber) Descriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{2}
}

func (x *ShowBookingNumber) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

// Guest confirms key pickup.
type ReceiveCottageKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Physical/digital cottage key ID.
	CottageKeyId  string `protobuf:"bytes,1,opt,name=cottage_key_id,json=cottageKeyId,proto3" json:"cottage_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCottageKey) Reset() {
	*x = ReceiveCottageKey{}
	mi := &file_lodging_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCottageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCottageKey) ProtoMessage() {}

func (x *ReceiveCottageKey) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCottageKey.ProtoReflect.Descriptor instead.
func (*ReceiveCottageKey) Descriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiveCottageKey) GetCottageKeyId() string {
	if x != nil {
		return x.CottageKeyId
	}
	return ""
}

// Guest confirms key return.
type ReturnCottageKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Physical/digital cottage key ID.
	CottageKeyId  string `protobuf:"bytes,1,opt,name=cottage_key_id,json=cottageKeyId,proto3" json:"cottage_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnCottageKey) Reset() {
	*x = ReturnCottageKey{}
	mi := &file_lodging_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnCottageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnCottageKey) ProtoMessage() {}

func (x *ReturnCottageKey) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnCottageKey.ProtoReflect.Descriptor instead.
func (*ReturnCottageKey) Descriptor() ([]byte, []int) {
	return file_lodging_guest_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnCottageKey) GetCottageKeyId() string {
	if x != nil {
		return x.CottageKeyId
	}
	return ""
}

var File_lodging_guest_proto protoreflect.FileDescriptor

const file_lodging_guest_proto_rawDesc = "" +
	"\n" +
	"\x13lodging/guest.proto\x12\n" +
	"lodging.v1\"\xcb\x02\n" +
	"\rGuestResponse\x12?\n" +
	"\rshow_document\x18\x01 \x01(\v2\x18.lodging.v1.ShowDocumentH\x00R\fshowDocument\x12O\n" +
	"\x13show_booking_number\x18\x02 \x01(\v2\x1d.lodging.v1.ShowBookingNumberH\x00R\x11showBookingNumber\x12O\n" +
	"\x13receive_cottage_key\x18\x03 \x01(\v2\x1d.lodging.v1.ReceiveCottageKeyH\x00R\x11receiveCottageKey\x12L\n" +
	"\x12return_cottage_key\x18\x04 \x01(\v2\x1c.lodging.v1.ReturnCottageKeyH\x00R\x10returnCottageKeyB\t\n" +
	"\apayload\"/\n" +
	"\fShowDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"2\n" +
	"\x11ShowBookingNumber\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"9\n" +
	"\x11ReceiveCottageKey\x12$\n" +
	"\x0ecottage_key_id\x18\x01 \x01(\tR\fcottageKeyId\"8\n" +
	"\x10ReturnCottageKey\x12$\n" +
	"\x0ecottage_key_id\x18\x01 \x01(\tR\fcottageKeyId*\xfb\x02\n" +
	"\vGuestAction\x12\x1c\n" +
	"\x18GUEST_ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SHOW_FOR_CHECKIN\x10\x01\x12\x11\n" +
	"\rSHOW_DOCUMENT\x10\x02\x12\x17\n" +
	"\x13SHOW_BOOKING_NUMBER\x10\x03\x12\x11\n" +
	"\rENTER_COTTAGE\x10\x04\x12\x11\n" +
	"\rLEAVE_COTTAGE\x10\x05\x12\x11\n" +
	"\rGO_FOR_A_BATH\x10\x06\x12\x14\n" +
	"\x10RETURN_FROM_BATH\x10\a\x12\x11\n" +
	"\rGO_FOR_DINNER\x10\b\x12\x14\n" +
	"\x10GO_FOR_BREAKFAST\x10\t\x12\x0f\n" +
	"\vGO_TO_SLEEP\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06WAKEUP\x10\v\x12\x1e\n" +
	"\x1aLEAVE_CLEANUP_NOTIFICATION\x10\f\x12\x10\n" +
	"\fENJOY_RESORT\x10\r\x12\x17\n" +
	"\x13PROCEED_TO_CHECKOUT\x10\x0e\x12\x16\n" +
	"\x12RETURN_COTTAGE_KEY\x10\x0f\x12\x14\n" +
	"\x10TAKE_COTTAGE_KEY\x10\x10BJZHgithub.com/Kenji-Uema/guestSimulator/internal/domain/dto/lodging;lodgingb\x06proto3"

var (
	file_lodging_guest_proto_rawDescOnce sync.Once
	file_lodging_guest_proto_rawDescData []byte
)

func file_lodging_guest_proto_rawDescGZIP() []byte {
	file_lodging_guest_proto_rawDescOnce.Do(func() {
		file_lodging_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lodging_guest_proto_rawDesc), len(file_lodging_guest_proto_rawDesc)))
	})
	return file_lodging_guest_proto_rawDescData
}

var file_lodging_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lodging_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lodging_guest_proto_goTypes = []any{
	(GuestAction)(0),          // 0: lodging.v1.GuestAction
	(*GuestResponse)(nil),     // 1: lodging.v1.GuestResponse
	(*ShowDocument)(nil),      // 2: lodging.v1.ShowDocument
	(*ShowBookingNumber)(nil), // 3: lodging.v1.ShowBookingNumber
	(*ReceiveCottageKey)(nil), // 4: lodging.v1.ReceiveCottageKey
	(*ReturnCottageKey)(nil),  // 5: lodging.v1.ReturnCottageKey
}
var file_lodging_guest_proto_depIdxs = []int32{
	2, // 0: lodging.v1.GuestResponse.show_document:type_name -> lodging.v1.ShowDocument
	3, // 1: lodging.v1.GuestResponse.show_booking_number:type_name -> lodging.v1.ShowBookingNumber
	4, // 2: lodging.v1.GuestResponse.receive_cottage_key:type_name -> lodging.v1.ReceiveCottageKey
	5, // 3: lodging.v1.GuestResponse.return_cottage_key:type_name -> lodging.v1.ReturnCottageKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lodging_guest_proto_init() }
func file_lodging_guest_proto_init() {
	if File_lodging_guest_proto != nil {
		return
	}
	file_lodging_guest_proto_msgTypes[0].OneofWrappers = []any{
		(*GuestResponse_ShowDocument)(nil),
		(*GuestResponse_ShowBookingNumber)(nil),
		(*GuestResponse_ReceiveCottageKey)(nil),
		(*GuestResponse_ReturnCottageKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lodging_guest_proto_rawDesc), len(file_lodging_guest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lodging_guest_proto_goTypes,
		DependencyIndexes: file_lodging_guest_proto_depIdxs,
		EnumInfos:         file_lodging_guest_proto_enumTypes,
		MessageInfos:      file_lodging_guest_proto_msgTypes,
	}.Build()
	File_lodging_guest_proto = out.File
	file_lodging_guest_proto_goTypes = nil
	file_lodging_guest_proto_depIdxs = nil
}
