// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lodging/system.proto

package lodging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notifications sent by the system to drive guest flow.
type SystemNotification int32

const (
	// Default zero value.
	SystemNotification_SYSTEM_NOTIFICATION_UNSPECIFIED SystemNotification = 0
	// System is validating booking information.
	SystemNotification_BOOKING_CHECKING SystemNotification = 1
	// Check-in completed successfully.
	SystemNotification_CHECK_IN_COMPLETE SystemNotification = 2
	// Dinner is available.
	SystemNotification_DINNER_READY SystemNotification = 3
	// System asks guest to prepare cottage for sleep mode.
	SystemNotification_PREPARE_COTTAGE_TO_SLEEP SystemNotification = 4
	// Breakfast is available.
	SystemNotification_BREAKFAST_READY SystemNotification = 5
	// Checkout reminder for next day.
	SystemNotification_CHECK_OUT_TOMORROW SystemNotification = 6
	SystemNotification_CHECK_OUT_COMPLETE SystemNotification = 7
	// Checkout is due today.
	SystemNotification_CHECK_OUT_TODAY SystemNotification = 8
)

// Enum value maps for SystemNotification.
var (
	SystemNotification_name = map[int32]string{
		0: "SYSTEM_NOTIFICATION_UNSPECIFIED",
		1: "BOOKING_CHECKING",
		2: "CHECK_IN_COMPLETE",
		3: "DINNER_READY",
		4: "PREPARE_COTTAGE_TO_SLEEP",
		5: "BREAKFAST_READY",
		6: "CHECK_OUT_TOMORROW",
		7: "CHECK_OUT_COMPLETE",
		8: "CHECK_OUT_TODAY",
	}
	SystemNotification_value = map[string]int32{
		"SYSTEM_NOTIFICATION_UNSPECIFIED": 0,
		"BOOKING_CHECKING":                1,
		"CHECK_IN_COMPLETE":               2,
		"DINNER_READY":                    3,
		"PREPARE_COTTAGE_TO_SLEEP":        4,
		"BREAKFAST_READY":                 5,
		"CHECK_OUT_TOMORROW":              6,
		"CHECK_OUT_COMPLETE":              7,
		"CHECK_OUT_TODAY":                 8,
	}
)

func (x SystemNotification) Enum() *SystemNotification {
	p := new(SystemNotification)
	*p = x
	return p
}

func (x SystemNotification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemNotification) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_system_proto_enumTypes[0].Descriptor()
}

func (SystemNotification) Type() protoreflect.EnumType {
	return &file_lodging_system_proto_enumTypes[0]
}

func (x SystemNotification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemNotification.Descriptor instead.
func (SystemNotification) EnumDescriptor() ([]byte, []int) {
	return file_lodging_system_proto_rawDescGZIP(), []int{0}
}

// Requests sent by the system that require guest data/action.
type SystemRequest int32

const (
	// Default zero value.
	SystemRequest_SYSTEM_REQUEST_UNSPECIFIED SystemRequest = 0
	// Request guest document identifier.
	SystemRequest_REQUEST_DOCUMENT SystemRequest = 1
	// Request guest booking identifier.
	SystemRequest_REQUEST_BOOKING_NUMBER SystemRequest = 2
	// Instruct guest to take the cottage key.
	SystemRequest_GIVE_COTTAGE_KEY SystemRequest = 3
	// Request guest to return the cottage key.
	SystemRequest_REQUEST_COTTAGE_KEY SystemRequest = 4
)

// Enum value maps for SystemRequest.
var (
	SystemRequest_name = map[int32]string{
		0: "SYSTEM_REQUEST_UNSPECIFIED",
		1: "REQUEST_DOCUMENT",
		2: "REQUEST_BOOKING_NUMBER",
		3: "GIVE_COTTAGE_KEY",
		4: "REQUEST_COTTAGE_KEY",
	}
	SystemRequest_value = map[string]int32{
		"SYSTEM_REQUEST_UNSPECIFIED": 0,
		"REQUEST_DOCUMENT":           1,
		"REQUEST_BOOKING_NUMBER":     2,
		"GIVE_COTTAGE_KEY":           3,
		"REQUEST_COTTAGE_KEY":        4,
	}
)

func (x SystemRequest) Enum() *SystemRequest {
	p := new(SystemRequest)
	*p = x
	return p
}

func (x SystemRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_system_proto_enumTypes[1].Descriptor()
}

func (SystemRequest) Type() protoreflect.EnumType {
	return &file_lodging_system_proto_enumTypes[1]
}

func (x SystemRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemRequest.Descriptor instead.
func (SystemRequest) EnumDescriptor() ([]byte, []int) {
	return file_lodging_system_proto_rawDescGZIP(), []int{1}
}

var File_lodging_system_proto protoreflect.FileDescriptor

const file_lodging_system_proto_rawDesc = "" +
	"\n" +
	"\x14lodging/system.proto\x12\n" +
	"lodging.v1*\xf0\x01\n" +
	"\x12SystemNotification\x12#\n" +
	"\x1fSYSTEM_NOTIFICATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BOOKING_CHECKING\x10\x01\x12\x15\n" +
	"\x11CHECK_IN_COMPLETE\x10\x02\x12\x10\n" +
	"\fDINNER_READY\x10\x03\x12\x1c\n" +
	"\x18PREPARE_COTTAGE_TO_SLEEP\x10\x04\x12\x13\n" +
	"\x0fBREAKFAST_READY\x10\x05\x12\x16\n" +
	"\x12CHECK_OUT_TOMORROW\x10\x06\x12\x16\n" +
	"\x12CHECK_OUT_COMPLETE\x10\a\x12\x13\n" +
	"\x0fCHECK_OUT_TODAY\x10\b*\x90\x01\n" +
	"\rSystemRequest\x12\x1e\n" +
	"\x1aSYSTEM_REQUEST_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REQUEST_DOCUMENT\x10\x01\x12\x1a\n" +
	"\x16REQUEST_BOOKING_NUMBER\x10\x02\x12\x14\n" +
	"\x10GIVE_COTTAGE_KEY\x10\x03\x12\x17\n" +
	"\x13REQUEST_COTTAGE_KEY\x10\x04BJZHgithub.com/Kenji-Uema/guestSimulator/internal/domain/dto/lodging;lodgingb\x06proto3"

var (
	file_lodging_system_proto_rawDescOnce sync.Once
	file_lodging_system_proto_rawDescData []byte
)

func file_lodging_system_proto_rawDescGZIP() []byte {
	file_lodging_system_proto_rawDescOnce.Do(func() {
		file_lodging_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lodging_system_proto_rawDesc), len(file_lodging_system_proto_rawDesc)))
	})
	return file_lodging_system_proto_rawDescData
}

var file_lodging_system_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lodging_system_proto_goTypes = []any{
	(SystemNotification)(0), // 0: lodging.v1.SystemNotification
	(SystemRequest)(0),      // 1: lodging.v1.SystemRequest
}
var file_lodging_system_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lodging_system_proto_init() }
func file_lodging_system_proto_init() {
	if File_lodging_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lodging_system_proto_rawDesc), len(file_lodging_system_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lodging_system_proto_goTypes,
		DependencyIndexes: file_lodging_system_proto_depIdxs,
		EnumInfos:         file_lodging_system_proto_enumTypes,
	}.Build()
	File_lodging_system_proto = out.File
	file_lodging_system_proto_goTypes = nil
	file_lodging_system_proto_depIdxs = nil
}
