// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: communication/booking_confirmation.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_CANCELLED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_communication_booking_confirmation_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_communication_booking_confirmation_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_communication_booking_confirmation_proto_rawDescGZIP(), []int{0}
}

type BookingConfirmedNotificationEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId     string                      `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BookingStatus BookingStatus               `protobuf:"varint,4,opt,name=booking_status,json=bookingStatus,proto3,enum=communication.v1.BookingStatus" json:"booking_status,omitempty"`
	Guest         *Guest                      `protobuf:"bytes,5,opt,name=guest,proto3" json:"guest,omitempty"`
	Booking       *BookingConfirmationSummary `protobuf:"bytes,6,opt,name=booking,proto3" json:"booking,omitempty"`
	ConfirmedAt   *timestamppb.Timestamp      `protobuf:"bytes,8,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingConfirmedNotificationEvent) Reset() {
	*x = BookingConfirmedNotificationEvent{}
	mi := &file_communication_booking_confirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingConfirmedNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirmedNotificationEvent) ProtoMessage() {}

func (x *BookingConfirmedNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_communication_booking_confirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirmedNotificationEvent.ProtoReflect.Descriptor instead.
func (*BookingConfirmedNotificationEvent) Descriptor() ([]byte, []int) {
	return file_communication_booking_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *BookingConfirmedNotificationEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingConfirmedNotificationEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingConfirmedNotificationEvent) GetBookingStatus() BookingStatus {
	if x != nil {
		return x.BookingStatus
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *BookingConfirmedNotificationEvent) GetGuest() *Guest {
	if x != nil {
		return x.Guest
	}
	return nil
}

func (x *BookingConfirmedNotificationEvent) GetBooking() *BookingConfirmationSummary {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *BookingConfirmedNotificationEvent) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type Guest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestId       string                 `protobuf:"bytes,1,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guest) Reset() {
	*x = Guest{}
	mi := &file_communication_booking_confirmation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guest) ProtoMessage() {}

func (x *Guest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_booking_confirmation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guest.ProtoReflect.Descriptor instead.
func (*Guest) Descriptor() ([]byte, []int) {
	return file_communication_booking_confirmation_proto_rawDescGZIP(), []int{1}
}

func (x *Guest) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *Guest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Guest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type BookingConfirmationSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CottageName    string                 `protobuf:"bytes,1,opt,name=cottage_name,json=cottageName,proto3" json:"cottage_name,omitempty"`
	CheckIn        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Nights         int32                  `protobuf:"varint,4,opt,name=nights,proto3" json:"nights,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,5,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingConfirmationSummary) Reset() {
	*x = BookingConfirmationSummary{}
	mi := &file_communication_booking_confirmation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingConfirmationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirmationSummary) ProtoMessage() {}

func (x *BookingConfirmationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_communication_booking_confirmation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirmationSummary.ProtoReflect.Descriptor instead.
func (*BookingConfirmationSummary) Descriptor() ([]byte, []int) {
	return file_communication_booking_confirmation_proto_rawDescGZIP(), []int{2}
}

func (x *BookingConfirmationSummary) GetCottageName() string {
	if x != nil {
		return x.CottageName
	}
	return ""
}

func (x *BookingConfirmationSummary) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *BookingConfirmationSummary) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *BookingConfirmationSummary) GetNights() int32 {
	if x != nil {
		return x.Nights
	}
	return 0
}

func (x *BookingConfirmationSummary) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

var File_communication_booking_confirmation_proto protoreflect.FileDescriptor

const file_communication_booking_confirmation_proto_rawDesc = "" +
	"\n" +
	"(communication/booking_confirmation.proto\x12\x10communication.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"!BookingConfirmedNotificationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12F\n" +
	"\x0ebooking_status\x18\x04 \x01(\x0e2\x1f.communication.v1.BookingStatusR\rbookingStatus\x12-\n" +
	"\x05guest\x18\x05 \x01(\v2\x17.communication.v1.GuestR\x05guest\x12F\n" +
	"\abooking\x18\x06 \x01(\v2,.communication.v1.BookingConfirmationSummaryR\abooking\x12=\n" +
	"\fconfirmed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\"b\n" +
	"\x05Guest\x12\x19\n" +
	"\bguest_id\x18\x01 \x01(\tR\aguestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\xf1\x01\n" +
	"\x1aBookingConfirmationSummary\x12!\n" +
	"\fcottage_name\x18\x01 \x01(\tR\vcottageName\x125\n" +
	"\bcheck_in\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x16\n" +
	"\x06nights\x18\x04 \x01(\x05R\x06nights\x12(\n" +
	"\x10number_of_guests\x18\x05 \x01(\x05R\x0enumberOfGuests*\x87\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03B]Z[github.com/Kenji-Uema/guestSimulator/internal/transport/grpc/pb/communication;communicationb\x06proto3"

var (
	file_communication_booking_confirmation_proto_rawDescOnce sync.Once
	file_communication_booking_confirmation_proto_rawDescData []byte
)

func file_communication_booking_confirmation_proto_rawDescGZIP() []byte {
	file_communication_booking_confirmation_proto_rawDescOnce.Do(func() {
		file_communication_booking_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_booking_confirmation_proto_rawDesc), len(file_communication_booking_confirmation_proto_rawDesc)))
	})
	return file_communication_booking_confirmation_proto_rawDescData
}

var file_communication_booking_confirmation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_communication_booking_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_communication_booking_confirmation_proto_goTypes = []any{
	(BookingStatus)(0),                        // 0: communication.v1.BookingStatus
	(*BookingConfirmedNotificationEvent)(nil), // 1: communication.v1.BookingConfirmedNotificationEvent
	(*Guest)(nil),                             // 2: communication.v1.Guest
	(*BookingConfirmationSummary)(nil),        // 3: communication.v1.BookingConfirmationSummary
	(*timestamppb.Timestamp)(nil),             // 4: google.protobuf.Timestamp
}
var file_communication_booking_confirmation_proto_depIdxs = []int32{
	0, // 0: communication.v1.BookingConfirmedNotificationEvent.booking_status:type_name -> communication.v1.BookingStatus
	2, // 1: communication.v1.BookingConfirmedNotificationEvent.guest:type_name -> communication.v1.Guest
	3, // 2: communication.v1.BookingConfirmedNotificationEvent.booking:type_name -> communication.v1.BookingConfirmationSummary
	4, // 3: communication.v1.BookingConfirmedNotificationEvent.confirmed_at:type_name -> google.protobuf.Timestamp
	4, // 4: communication.v1.BookingConfirmationSummary.check_in:type_name -> google.protobuf.Timestamp
	4, // 5: communication.v1.BookingConfirmationSummary.check_out:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_communication_booking_confirmation_proto_init() }
func file_communication_booking_confirmation_proto_init() {
	if File_communication_booking_confirmation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_booking_confirmation_proto_rawDesc), len(file_communication_booking_confirmation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_communication_booking_confirmation_proto_goTypes,
		DependencyIndexes: file_communication_booking_confirmation_proto_depIdxs,
		EnumInfos:         file_communication_booking_confirmation_proto_enumTypes,
		MessageInfos:      file_communication_booking_confirmation_proto_msgTypes,
	}.Build()
	File_communication_booking_confirmation_proto = out.File
	file_communication_booking_confirmation_proto_goTypes = nil
	file_communication_booking_confirmation_proto_depIdxs = nil
}
