// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: communication/checkin_tomorrow.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInTomorrowNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookingId       string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	GuestId         string                 `protobuf:"bytes,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	CottageName     string                 `protobuf:"bytes,3,opt,name=cottage_name,json=cottageName,proto3" json:"cottage_name,omitempty"`
	CheckIn         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	NumberOfGuests  int32                  `protobuf:"varint,6,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	NotificationDay *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=notification_day,json=notificationDay,proto3" json:"notification_day,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckInTomorrowNotification) Reset() {
	*x = CheckInTomorrowNotification{}
	mi := &file_communication_checkin_tomorrow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInTomorrowNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInTomorrowNotification) ProtoMessage() {}

func (x *CheckInTomorrowNotification) ProtoReflect() protoreflect.Message {
	mi := &file_communication_checkin_tomorrow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInTomorrowNotification.ProtoReflect.Descriptor instead.
func (*CheckInTomorrowNotification) Descriptor() ([]byte, []int) {
	return file_communication_checkin_tomorrow_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInTomorrowNotification) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CheckInTomorrowNotification) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *CheckInTomorrowNotification) GetCottageName() string {
	if x != nil {
		return x.CottageName
	}
	return ""
}

func (x *CheckInTomorrowNotification) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CheckInTomorrowNotification) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *CheckInTomorrowNotification) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

func (x *CheckInTomorrowNotification) GetNotificationDay() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationDay
	}
	return nil
}

var File_communication_checkin_tomorrow_proto protoreflect.FileDescriptor

const file_communication_checkin_tomorrow_proto_rawDesc = "" +
	"\n" +
	"$communication/checkin_tomorrow.proto\x12\n" +
	"lodging.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x1bCheckInTomorrowNotification\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x19\n" +
	"\bguest_id\x18\x02 \x01(\tR\aguestId\x12!\n" +
	"\fcottage_name\x18\x03 \x01(\tR\vcottageName\x125\n" +
	"\bcheck_in\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12(\n" +
	"\x10number_of_guests\x18\x06 \x01(\x05R\x0enumberOfGuests\x12E\n" +
	"\x10notification_day\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fnotificationDayB]Z[github.com/Kenji-Uema/guestSimulator/internal/transport/grpc/pb/communication;communicationb\x06proto3"

var (
	file_communication_checkin_tomorrow_proto_rawDescOnce sync.Once
	file_communication_checkin_tomorrow_proto_rawDescData []byte
)

func file_communication_checkin_tomorrow_proto_rawDescGZIP() []byte {
	file_communication_checkin_tomorrow_proto_rawDescOnce.Do(func() {
		file_communication_checkin_tomorrow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_checkin_tomorrow_proto_rawDesc), len(file_communication_checkin_tomorrow_proto_rawDesc)))
	})
	return file_communication_checkin_tomorrow_proto_rawDescData
}

var file_communication_checkin_tomorrow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_communication_checkin_tomorrow_proto_goTypes = []any{
	(*CheckInTomorrowNotification)(nil), // 0: lodging.v1.CheckInTomorrowNotification
	(*timestamppb.Timestamp)(nil),       // 1: google.protobuf.Timestamp
}
var file_communication_checkin_tomorrow_proto_depIdxs = []int32{
	1, // 0: lodging.v1.CheckInTomorrowNotification.check_in:type_name -> google.protobuf.Timestamp
	1, // 1: lodging.v1.CheckInTomorrowNotification.check_out:type_name -> google.protobuf.Timestamp
	1, // 2: lodging.v1.CheckInTomorrowNotification.notification_day:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_communication_checkin_tomorrow_proto_init() }
func file_communication_checkin_tomorrow_proto_init() {
	if File_communication_checkin_tomorrow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_checkin_tomorrow_proto_rawDesc), len(file_communication_checkin_tomorrow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_communication_checkin_tomorrow_proto_goTypes,
		DependencyIndexes: file_communication_checkin_tomorrow_proto_depIdxs,
		MessageInfos:      file_communication_checkin_tomorrow_proto_msgTypes,
	}.Build()
	File_communication_checkin_tomorrow_proto = out.File
	file_communication_checkin_tomorrow_proto_goTypes = nil
	file_communication_checkin_tomorrow_proto_depIdxs = nil
}
