// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: communication/payment_request.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceNumber string                 `protobuf:"bytes,1,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Total         *Money                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Booking       *BookingSummary        `protobuf:"bytes,6,opt,name=booking,proto3" json:"booking,omitempty"`
	Payer         *PayerSummary          `protobuf:"bytes,7,opt,name=payer,proto3" json:"payer,omitempty"`
	Options       []*PaymentOption       `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_communication_payment_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_payment_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_communication_payment_request_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *PaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentRequest) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *PaymentRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *PaymentRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PaymentRequest) GetBooking() *BookingSummary {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *PaymentRequest) GetPayer() *PayerSummary {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *PaymentRequest) GetOptions() []*PaymentOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_communication_payment_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_communication_payment_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_communication_payment_request_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	Instructions  string                 `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOption) Reset() {
	*x = PaymentOption{}
	mi := &file_communication_payment_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOption) ProtoMessage() {}

func (x *PaymentOption) ProtoReflect() protoreflect.Message {
	mi := &file_communication_payment_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOption.ProtoReflect.Descriptor instead.
func (*PaymentOption) Descriptor() ([]byte, []int) {
	return file_communication_payment_request_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentOption) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentOption) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *PaymentOption) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type BookingSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CottageName    string                 `protobuf:"bytes,2,opt,name=cottage_name,json=cottageName,proto3" json:"cottage_name,omitempty"`
	Nights         int32                  `protobuf:"varint,3,opt,name=nights,proto3" json:"nights,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,4,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingSummary) Reset() {
	*x = BookingSummary{}
	mi := &file_communication_payment_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSummary) ProtoMessage() {}

func (x *BookingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_communication_payment_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSummary.ProtoReflect.Descriptor instead.
func (*BookingSummary) Descriptor() ([]byte, []int) {
	return file_communication_payment_request_proto_rawDescGZIP(), []int{3}
}

func (x *BookingSummary) GetCottageName() string {
	if x != nil {
		return x.CottageName
	}
	return ""
}

func (x *BookingSummary) GetNights() int32 {
	if x != nil {
		return x.Nights
	}
	return 0
}

func (x *BookingSummary) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type PayerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayerSummary) Reset() {
	*x = PayerSummary{}
	mi := &file_communication_payment_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayerSummary) ProtoMessage() {}

func (x *PayerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_communication_payment_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayerSummary.ProtoReflect.Descriptor instead.
func (*PayerSummary) Descriptor() ([]byte, []int) {
	return file_communication_payment_request_proto_rawDescGZIP(), []int{4}
}

func (x *PayerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PayerSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_communication_payment_request_proto protoreflect.FileDescriptor

const file_communication_payment_request_proto_rawDesc = "" +
	"\n" +
	"#communication/payment_request.proto\x12\x10communication.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x03\n" +
	"\x0ePaymentRequest\x12%\n" +
	"\x0einvoice_number\x18\x01 \x01(\tR\rinvoiceNumber\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x05total\x18\x03 \x01(\v2\x17.communication.v1.MoneyR\x05total\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\abooking\x18\x06 \x01(\v2 .communication.v1.BookingSummaryR\abooking\x124\n" +
	"\x05payer\x18\a \x01(\v2\x1e.communication.v1.PayerSummaryR\x05payer\x129\n" +
	"\aoptions\x18\b \x03(\v2\x1f.communication.v1.PaymentOptionR\aoptions\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"l\n" +
	"\rPaymentOption\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\"u\n" +
	"\x0eBookingSummary\x12!\n" +
	"\fcottage_name\x18\x02 \x01(\tR\vcottageName\x12\x16\n" +
	"\x06nights\x18\x03 \x01(\x05R\x06nights\x12(\n" +
	"\x10number_of_guests\x18\x04 \x01(\x05R\x0enumberOfGuests\"8\n" +
	"\fPayerSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05emailBVZTgithub.com/Kenji-Uema/guestSimulator/internal/domain/dto/communication;communicationb\x06proto3"

var (
	file_communication_payment_request_proto_rawDescOnce sync.Once
	file_communication_payment_request_proto_rawDescData []byte
)

func file_communication_payment_request_proto_rawDescGZIP() []byte {
	file_communication_payment_request_proto_rawDescOnce.Do(func() {
		file_communication_payment_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_payment_request_proto_rawDesc), len(file_communication_payment_request_proto_rawDesc)))
	})
	return file_communication_payment_request_proto_rawDescData
}

var file_communication_payment_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_communication_payment_request_proto_goTypes = []any{
	(*PaymentRequest)(nil),        // 0: communication.v1.PaymentRequest
	(*Money)(nil),                 // 1: communication.v1.Money
	(*PaymentOption)(nil),         // 2: communication.v1.PaymentOption
	(*BookingSummary)(nil),        // 3: communication.v1.BookingSummary
	(*PayerSummary)(nil),          // 4: communication.v1.PayerSummary
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_communication_payment_request_proto_depIdxs = []int32{
	1, // 0: communication.v1.PaymentRequest.total:type_name -> communication.v1.Money
	5, // 1: communication.v1.PaymentRequest.issued_at:type_name -> google.protobuf.Timestamp
	5, // 2: communication.v1.PaymentRequest.expires_at:type_name -> google.protobuf.Timestamp
	3, // 3: communication.v1.PaymentRequest.booking:type_name -> communication.v1.BookingSummary
	4, // 4: communication.v1.PaymentRequest.payer:type_name -> communication.v1.PayerSummary
	2, // 5: communication.v1.PaymentRequest.options:type_name -> communication.v1.PaymentOption
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_communication_payment_request_proto_init() }
func file_communication_payment_request_proto_init() {
	if File_communication_payment_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_payment_request_proto_rawDesc), len(file_communication_payment_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_communication_payment_request_proto_goTypes,
		DependencyIndexes: file_communication_payment_request_proto_depIdxs,
		MessageInfos:      file_communication_payment_request_proto_msgTypes,
	}.Build()
	File_communication_payment_request_proto = out.File
	file_communication_payment_request_proto_goTypes = nil
	file_communication_payment_request_proto_depIdxs = nil
}
